### ISSUE TITLE
Use app-owned account registration

### ISSUE THREAD

**Issue by bgins** [fission-codes/auth-lobby#111]
# Summary

## Problem

The auth lobby does not use app-owned account registration from webnative.

### Impact

No immediate impact. In the long term, account registration may change or receive patches, and we will want only want to maintain the code in one place.

## Solution

Replace account registration with the lobby implementation in https://github.com/fission-suite/webnative/blob/main/src/auth/lobby.ts. The lobby implementation is incomplete and will need a bit more work.

**Comment by icidasset** [comment]
Done in #120
