### ISSUE TITLE
Use app-owned account linking

### ISSUE THREAD

**Issue by bgins** [fission-codes/auth-lobby#112]
# Summary

## Problem

The auth lobby does not use app-owned account linking from webnative.

### Impact

No immediate impact. In the long term, account linking may change or receive patches, and we will want only want to maintain the code in one place.

## Solution

Replace account registration with the lobby implementation in https://github.com/fission-suite/webnative/blob/main/src/auth/lobby.ts. We should wait until https://github.com/fission-suite/webnative/pull/360 is merged.

**Comment by icidasset** [comment]
Done in #120
